#!/bin/sh
## BadlionClient freezes on "Checking for Client Update" if this is not set
export APPIMAGE=1

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-net.badlion.BadlionClient}"

declare -a FLAGS=(--enable-speech-dispatcher)

if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
    if [[ -c /dev/nvidia0 ]]; then
        FLAGS+=(--disable-gpu-sandbox)
    fi

    WAYLAND_SOCKET=${WAYLAND_DISPLAY:-"wayland-0"}
    if [[ "${WAYLAND_SOCKET:0:1}" != "/" ]]; then
        WAYLAND_SOCKET="$XDG_RUNTIME_DIR/$WAYLAND_SOCKET"
    fi

    if [[ -e "$WAYLAND_SOCKET" ]]; then
        FLAGS+=(--ozone-platform-hint=auto)
        FLAGS+=(--enable-wayland-ime)
    fi
fi

zypak-wrapper /app/extra/BadlionClient.bin "${FLAGS[@]}" "$@"
