name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Archi.flatpak
          manifest-path: com.archimatetool.Archi.yaml
          cache-key: flatpak-builder-${{ github.sha }}
